# Generated by Django 4.1.3 on 2023-01-22 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='choice',
        ),
    ]
