# Generated by Django 4.1.3 on 2023-01-22 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_product_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='choice',
            field=models.CharField(choices=[('XS', 'Xs'), ('X', 'X'), ('M', 'M'), ('L', 'L'), ('XL', 'Xl')], default='XL', max_length=55),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('Black', 'Black'), ('White', 'White'), ('Red', 'Red'), ('Blue', 'Blue'), ('Green', 'Green')], default='White', max_length=25),
        ),
    ]
