# Generated by Django 4.1.3 on 2023-01-22 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_product_choice_alter_product_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='choice',
        ),
    ]
