# Generated by Django 4.1.3 on 2023-01-22 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_product_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('Black', 'Black'), ('White', 'White'), ('Red', 'Red'), ('Blue', 'Blue'), ('Green', 'Green'), ('GREY', 'Grey'), ('YELLOW', 'Yellow'), ('BROWN', 'Brown')], default='White', max_length=25),
        ),
    ]
