# Generated by Django 4.1.3 on 2023-01-22 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_product_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='choice',
            field=models.CharField(choices=[('XS', 'Xs'), ('X', 'X'), ('M', 'M'), ('L', 'L'), ('XL', 'Xl')], default='XL', max_length=55),
        ),
    ]
